version: "3.8"
services:
  # I have no clue, but https://medium.com/@SabujJanaCodes/hands-on-haproxy-loadbalancing-with-go-and-docker-compose-part-1-71ce6551f601
  tbank-url-shortener:
    container_name: tbank-url-shortener
    # Traefik Detects New Services and Creates the Route for You
    labels:
      - "traefik.http.routers.tbank-url-shortener.rule=Host(`tbank.urlshortener.localhost`)"
    build:
      dockerfile: ./build/backend/Dockerfile
    #    image: # tbank_url_shortener:0.1.0
    environment:  # For App Config
      REDIS_HOST: "tbank-redis" # redis container name
      REDIS_PORT: "6379"        #

      CLICKHOUSE_USER: "oleg"
      CLICKHOUSE_PASSWORD: "tinkoff"
      CLICKHOUSE_DB: "tbank_academy"
      CLICKHOUSE_HOST: "tbank-clickhouse"
      CLICKHOUSE_PORT: "9000"
    ports:
      - "1323:1323"
    expose:
      - "1323:1323"
    networks:
      - tbank-network
    depends_on:
      - tbank-clickhouse
      - tbank-redis

  tbank-redis:
    container_name: "tbank-redis"
    image: redis
    ports:
      - "6379:6379"
    networks:
      - tbank-network

  tbank-clickhouse:
    container_name: "tbank-clickhouse"
    image: clickhouse/clickhouse-server:latest
    environment:
      CLICKHOUSE_USER: "oleg"
      CLICKHOUSE_PASSWORD: "tinkoff"
      CLICKHOUSE_DB: "tbank_academy"
      CLICKHOUSE_HOST: "tbank-clickhouse"
      CLICKHOUSE_PORT: "19000"
    ports:
      - "18123:8123"
      - "19000:9000"
    networks:
      - tbank-network
    volumes:
      - "./backend/migrations/20240615193939_short_to_long.sql:/docker-entrypoint-initdb.d/20240615193939_short_to_long.sql"

  tbank-prometheus:
    image: prom/prometheus:latest
    container_name: tbank-prometheus
    #restart: unless-stopped
    volumes:
      - ./build/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - "9090:9090"
    networks:
      - tbank-network

  tbank-grafana:
    image: grafana/grafana-oss:latest
    container_name: tbank-grafana
    labels:
      - "traefik.http.routers.tbank-grafana.rule=Host(`tbank.grafana.localhost`)"
    ports:
      - "3000:3000"
    networks:
      - tbank-network
    volumes:
      - "./build/grafana/provisioning/:/etc/grafana/provisioning/"
    # restart: unless-stopped

  tbank-traefik:
    # The official v3 Traefik docker image
    image: traefik:v3.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - tbank-network

networks:
  tbank-network:
    driver: bridge