apiVersion: v1
kind: ConfigMap
metadata:
  name: t-bank-url-shortener-cm
  namespace: t-bank-url-shortener
data:
  # envs
  app_port: "1323"
  redis_host: "redis.t-bank-storage" # statefulset.namespace
  redis_port: "6379"          # :containerPort from ...

  ch_host: "clikhouse.t-bank-storage"
  ch_port: "19000"